apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs-v0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.80
    path: "/mnt/nfs_share/v0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs-v1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.80
    path: "/mnt/nfs_share/v1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs-v2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.80
    path: "/mnt/nfs_share/v2"
---

